# Generated by Django 2.1.7 on 2020-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='immage', width_field='width_field')),
                ('context', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
